name: Node.js Project Deployment

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies
      - run: npm install

      # Step 4: Install PM2 globally
      - run: npm install pm2 -g

      # Step 5: Run tests (optional, based on your test setup)
      - run: npm test

  deploy:
    # Deploy only if build is successful
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code again in the deploy job
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies (in case any changes were made)
      - run: npm install

      # Step 4: Install PM2 globally if needed
      - run: npm install pm2 -g

      # Step 5: Stop existing PM2 processes (if any)
      - run: |
          pm2 stop all || true  # Continue even if no process exists

      # Step 6: Start your application using PM2
      - run: |
          pm2 start index.js --name "my-app"
