# name: Node.js Project Deployment

# on:
#     push:
#         branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # Step 1: Checkout the code
#       - uses: actions/checkout@v4

#       # Step 2: Set up Node.js environment
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       # Step 3: Install dependencies
#       - run: npm install

#       # Step 4: Install PM2 globally
#       - run: npm install pm2 -g

#   deploy:
#     # Deploy only if build is successful
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       # Step 1: Checkout the code again in the deploy job
#       - uses: actions/checkout@v4

#       # Step 2: Set up Node.js environment
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       # Step 3: Install dependencies (in case any changes were made)
#       - run: npm install

#       # Step 4: Install PM2 globally if needed
#       - run: npm install pm2 -g

#       # Step 5: Stop existing PM2 processes (if any)
#       - run: |
#           pm2 stop all || true  # Continue even if no process exists

#       # Step 6: Start your application using PM2
#       - run: |
#           pm2 start index.js --name "my-app"

name: Deploy to Azure App Service

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: renew-360-backend-app
          path: .

  deploy:
    runs-on:
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: renew-360-backend-app

        - name: Deploy to Azure App Service
          uses: azure/webapps-deploy@v2
          with:
            app-name: renew-360-backend
            publish-profile: ${{ secrets.AZURE_RENEW_360_PUBLISH_BACKEND }}
            package: .
